plugins {
    id 'com.android.application'
}

android {
    namespace "com.example.zabplay_player"
    compileSdk 34

    defaultConfig {
        applicationId "com.example.zabplay_player"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
}
